#!/usr/bin/env python3
"""
Comprehensive dictionary fix script for spelling bee game.
This script contains extensive word corrections for proper Traditional Chinese definitions
and grammatically correct example sentences suitable for Taiwanese English learners.
"""

import json
import os

# Comprehensive English-to-Traditional Chinese dictionary with example sentences
# Organized by common word patterns and categories
COMPREHENSIVE_DICTIONARY = {
    # Basic verbs - present tense
    "say": ("說", "She wants to say something important.", "動詞"),
    "get": ("得到、獲得", "I need to get some water.", "動詞"),
    "use": ("使用", "We use computers every day.", "動詞"),
    "ask": ("詢問", "You can ask questions anytime.", "動詞"),
    "put": ("放", "Please put your bag here.", "動詞"),
    "let": ("讓", "Let me help you with that.", "動詞"),
    "run": ("跑", "The children run in the park.", "動詞"),
    "sit": ("坐", "Please sit down and relax.", "動詞"),
    "pay": ("付款", "You can pay by credit card.", "動詞"),
    "set": ("設定、放置", "Please set the alarm for 7 AM.", "動詞"),
    "win": ("贏得", "Our team will win the game.", "動詞"),
    "buy": ("購買", "I want to buy a new book.", "動詞"),
    "die": ("死亡", "Plants will die without water.", "動詞"),
    "cut": ("切割", "Use scissors to cut the paper.", "動詞"),
    "try": ("嘗試", "You should try your best.", "動詞"),
    "see": ("看見", "I can see the ocean from here.", "動詞"),
    "come": ("來", "Please come to the party.", "動詞"),
    "make": ("製作", "I can make a cake.", "動詞"),
    "know": ("知道", "I know the answer.", "動詞"),
    "take": ("拿取", "Take your umbrella with you.", "動詞"),
    "find": ("找到", "I can't find my keys.", "動詞"),
    "give": ("給", "Please give me a pen.", "動詞"),
    "tell": ("告訴", "Tell me about your day.", "動詞"),
    "work": ("工作", "My parents work hard.", "動詞"),
    "call": ("打電話", "I will call you later.", "動詞"),
    "feel": ("感覺", "I feel happy today.", "動詞"),
    "leave": ("離開", "We leave at noon.", "動詞"),
    "keep": ("保持", "Keep your room clean.", "動詞"),
    "begin": ("開始", "The class will begin soon.", "動詞"),
    "seem": ("似乎", "You seem tired.", "動詞"),
    "help": ("幫助", "Can you help me?", "動詞"),
    "show": ("展示", "Show me your homework.", "動詞"),
    "hear": ("聽見", "I can hear music.", "動詞"),
    "play": ("玩耍", "Children play outside.", "動詞"),
    "move": ("移動", "We move next month.", "動詞"),
    "live": ("居住", "I live in Taipei.", "動詞"),
    "believe": ("相信", "I believe in you.", "動詞"),
    "bring": ("帶來", "Bring your textbook tomorrow.", "動詞"),
    "happen": ("發生", "Accidents can happen.", "動詞"),
    "write": ("寫", "I write in my diary.", "動詞"),
    "stand": ("站立", "Please stand up.", "動詞"),
    "lose": ("失去", "Don't lose hope.", "動詞"),
    "meet": ("見面", "Let's meet at 3 PM.", "動詞"),
    "include": ("包括", "The price includes tax.", "動詞"),
    "continue": ("繼續", "Please continue reading.", "動詞"),
    "learn": ("學習", "I learn something new daily.", "動詞"),
    "change": ("改變", "People can change.", "動詞"),
    "lead": ("領導", "She will lead the team.", "動詞"),
    "understand": ("理解", "I understand the lesson.", "動詞"),
    "watch": ("觀看", "I watch TV at night.", "動詞"),
    "follow": ("跟隨", "Follow me please.", "動詞"),
    "stop": ("停止", "Stop at the red light.", "動詞"),
    "create": ("創造", "Artists create beautiful works.", "動詞"),
    "speak": ("說話", "Please speak slowly.", "動詞"),
    "read": ("閱讀", "I read books every day.", "動詞"),
    "allow": ("允許", "My parents allow me to go.", "動詞"),
    "add": ("增加", "Add sugar to your tea.", "動詞"),
    "spend": ("花費", "I spend time with family.", "動詞"),
    "grow": ("成長", "Plants grow in spring.", "動詞"),
    "open": ("打開", "Open the window please.", "動詞"),
    "walk": ("走路", "I walk to school.", "動詞"),
    "offer": ("提供", "They offer free samples.", "動詞"),
    "remember": ("記得", "I remember your name.", "動詞"),
    "love": ("愛", "I love my family.", "動詞"),
    "consider": ("考慮", "Please consider this option.", "動詞"),
    "appear": ("出現", "Stars appear at night.", "動詞"),
    "produce": ("生產", "Factories produce goods.", "動詞"),
    "wait": ("等待", "Please wait here.", "動詞"),
    "serve": ("服務", "Waiters serve food.", "動詞"),
    "send": ("寄送", "I will send you an email.", "動詞"),
    "expect": ("期待", "I expect good results.", "動詞"),
    "build": ("建造", "They build houses.", "動詞"),
    "stay": ("停留", "Stay here for a moment.", "動詞"),
    "fall": ("掉落", "Leaves fall in autumn.", "動詞"),
    "reach": ("到達", "We reach school at 8.", "動詞"),
    "kill": ("殺死", "Don't kill insects.", "動詞"),
    "remain": ("保持", "Please remain seated.", "動詞"),
    "suggest": ("建議", "I suggest we leave early.", "動詞"),
    "raise": ("舉起", "Raise your hand to answer.", "動詞"),
    "pass": ("通過", "Time passes quickly.", "動詞"),
    "sell": ("販賣", "They sell fresh fruit.", "動詞"),
    "require": ("需要", "This job requires skill.", "動詞"),
    "report": ("報告", "Please report the problem.", "動詞"),
    "decide": ("決定", "I decide to stay home.", "動詞"),
    "pull": ("拉", "Pull the door to open.", "動詞"),

    # Past tense verbs
    "saw": ("看見（see的過去式）", "I saw a rainbow yesterday.", "動詞"),
    "ran": ("跑（run的過去式）", "She ran very fast in the race.", "動詞"),
    "met": ("見面（meet的過去式）", "We met at the coffee shop.", "動詞"),
    "led": ("領導（lead的過去式）", "He led the team to victory.", "動詞"),
    "won": ("贏得（win的過去式）", "Our school won the championship.", "動詞"),
    "got": ("得到（get的過去式）", "I got a present for my birthday.", "動詞"),
    "made": ("製作（make的過去式）", "She made cookies for us.", "動詞"),
    "came": ("來（come的過去式）", "They came to visit last week.", "動詞"),
    "went": ("去（go的過去式）", "We went to the beach.", "動詞"),
    "took": ("拿（take的過去式）", "He took his umbrella.", "動詞"),
    "gave": ("給（give的過去式）", "She gave me good advice.", "動詞"),
    "told": ("告訴（tell的過去式）", "He told me the truth.", "動詞"),
    "left": ("離開（leave的過去式）", "They left early this morning.", "動詞"),
    "felt": ("感覺（feel的過去式）", "I felt nervous before the test.", "動詞"),
    "kept": ("保持（keep的過去式）", "We kept the secret safe.", "動詞"),
    "began": ("開始（begin的過去式）", "The show began at 7 PM.", "動詞"),
    "heard": ("聽見（hear的過去式）", "I heard a strange noise.", "動詞"),
    "brought": ("帶來（bring的過去式）", "She brought lunch for everyone.", "動詞"),
    "wrote": ("寫（write的過去式）", "He wrote a letter to his friend.", "動詞"),
    "sat": ("坐（sit的過去式）", "We sat under the tree.", "動詞"),
    "stood": ("站（stand的過去式）", "Everyone stood when the teacher entered.", "動詞"),
    "lost": ("失去（lose的過去式）", "I lost my wallet yesterday.", "動詞"),
    "paid": ("付款（pay的過去式）", "She paid for the meal.", "動詞"),
    "sent": ("寄送（send的過去式）", "I sent you a message.", "動詞"),
    "built": ("建造（build的過去式）", "They built a new bridge.", "動詞"),
    "spent": ("花費（spend的過去式）", "We spent the day at the park.", "動詞"),
    "fell": ("掉落（fall的過去式）", "The book fell off the shelf.", "動詞"),
    "cut": ("切（cut的過去式/原形同形）", "I cut the paper with scissors.", "動詞"),
    "read": ("閱讀（read的過去式/拼寫同形但發音不同）", "She read the book last night.", "動詞"),
    "bought": ("購買（buy的過去式）", "I bought a new phone.", "動詞"),
    "thought": ("想（think的過去式）", "I thought about your question.", "動詞"),
    "found": ("找到（find的過去式）", "We found the missing cat.", "動詞"),
    "held": ("握住（hold的過去式）", "She held my hand tightly.", "動詞"),
    "spoke": ("說（speak的過去式）", "He spoke clearly and loudly.", "動詞"),
    "knew": ("知道（know的過去式）", "I knew the answer immediately.", "動詞"),

    # Nouns - common words
    "way": ("方法、道路", "This is the best way to solve it.", "名詞"),
    "time": ("時間", "We don't have much time left.", "名詞"),
    "year": ("年", "This year has been wonderful.", "名詞"),
    "day": ("日子、天", "Have a nice day!", "名詞"),
    "man": ("男人", "The man is wearing a suit.", "名詞"),
    "thing": ("事物", "This thing is very useful.", "名詞"),
    "life": ("生命、生活", "Life is full of surprises.", "名詞"),
    "world": ("世界", "The world is very big.", "名詞"),
    "hand": ("手", "Wash your hands before eating.", "名詞"),
    "part": ("部分", "This is an important part of the story.", "名詞"),
    "child": ("孩子", "Every child deserves love.", "名詞"),
    "eye": ("眼睛", "She has beautiful blue eyes.", "名詞"),
    "woman": ("女人", "The woman is a doctor.", "名詞"),
    "place": ("地方", "This is a nice place to visit.", "名詞"),
    "work": ("工作", "Finding work can be challenging.", "名詞"),
    "week": ("星期", "We have a test next week.", "名詞"),
    "case": ("情況、案例", "In this case, we should wait.", "名詞"),
    "point": ("點、要點", "You made a good point.", "名詞"),
    "government": ("政府", "The government makes laws.", "名詞"),
    "company": ("公司", "She works for a big company.", "名詞"),
    "number": ("數字", "What is your phone number?", "名詞"),
    "group": ("團體", "We worked in a small group.", "名詞"),
    "problem": ("問題", "We need to solve this problem.", "名詞"),
    "fact": ("事實", "That is an interesting fact.", "名詞"),
    "room": ("房間", "My room is very clean.", "名詞"),
    "water": ("水", "Drink plenty of water daily.", "名詞"),
    "money": ("金錢", "Money can't buy happiness.", "名詞"),
    "story": ("故事", "Tell me a bedtime story.", "名詞"),
    "month": ("月份", "June is my favorite month.", "名詞"),
    "right": ("權利、右邊", "Everyone has the right to speak.", "名詞"),
    "study": ("研究", "This study shows important results.", "名詞"),
    "book": ("書", "I'm reading an interesting book.", "名詞"),
    "word": ("字", "Look up the word in the dictionary.", "名詞"),
    "family": ("家庭", "Family is very important to me.", "名詞"),
    "business": ("生意、商業", "Business is doing well this year.", "名詞"),
    "name": ("名字", "My name is Amy.", "名詞"),
    "student": ("學生", "Every student should study hard.", "名詞"),
    "home": ("家", "Home is where the heart is.", "名詞"),
    "school": ("學校", "I go to school every day.", "名詞"),
    "mother": ("母親", "My mother cooks delicious food.", "名詞"),
    "father": ("父親", "My father is very kind.", "名詞"),
    "teacher": ("老師", "Our teacher is very patient.", "名詞"),
    "friend": ("朋友", "A true friend is precious.", "名詞"),
    "door": ("門", "Please close the door.", "名詞"),
    "window": ("窗戶", "Open the window for fresh air.", "名詞"),
    "food": ("食物", "This food tastes delicious.", "名詞"),
    "car": ("汽車", "My father drives a red car.", "名詞"),
    "house": ("房子", "They live in a big house.", "名詞"),
    "head": ("頭", "She nodded her head in agreement.", "名詞"),
    "music": ("音樂", "I love listening to music.", "名詞"),
    "area": ("區域", "This area is very safe.", "名詞"),
    "city": ("城市", "Taipei is a bustling city.", "名詞"),
    "country": ("國家", "Taiwan is a beautiful country.", "名詞"),
    "power": ("力量", "Knowledge is power.", "名詞"),
    "hour": ("小時", "The movie lasts two hours.", "名詞"),
    "line": ("線、隊伍", "Please stand in line.", "名詞"),
    "body": ("身體", "Exercise keeps your body healthy.", "名詞"),
    "face": ("臉", "She has a kind face.", "名詞"),
    "question": ("問題", "Do you have any questions?", "名詞"),
    "system": ("系統", "The system works efficiently.", "名詞"),
    "program": ("計劃、程式", "This is a useful program.", "名詞"),
    "level": ("等級、水平", "He reached the highest level.", "名詞"),
    "paper": ("紙張、論文", "Write your name on the paper.", "名詞"),
    "idea": ("想法", "That's a brilliant idea!", "名詞"),
    "information": ("資訊", "We need more information.", "名詞"),
    "service": ("服務", "Customer service is excellent.", "名詞"),
    "reason": ("理由", "There's a good reason for this.", "名詞"),
    "office": ("辦公室", "He works in an office.", "名詞"),
    "party": ("派對、政黨", "We're having a party tonight.", "名詞"),
    "health": ("健康", "Health is more important than wealth.", "名詞"),
    "person": ("人", "She is a kind person.", "名詞"),
    "moment": ("時刻", "Wait just a moment please.", "名詞"),
    "street": ("街道", "The street is very busy.", "名詞"),
    "table": ("桌子", "Put the book on the table.", "名詞"),
    "community": ("社區", "Our community is very friendly.", "名詞"),
    "class": ("班級", "We have English class today.", "名詞"),
    "history": ("歷史", "History teaches us many lessons.", "名詞"),
    "law": ("法律", "Everyone must follow the law.", "名詞"),
    "society": ("社會", "We live in a modern society.", "名詞"),

    # Adjectives
    "good": ("好的", "This is a good book.", "形容詞"),
    "new": ("新的", "I bought a new bike.", "形容詞"),
    "first": ("第一的", "This is my first time here.", "形容詞"),
    "last": ("最後的", "This is the last chance.", "形容詞"),
    "long": ("長的", "It's a long story.", "形容詞"),
    "great": ("偉大的", "That's a great idea!", "形容詞"),
    "little": ("小的", "I have a little cat.", "形容詞"),
    "own": ("自己的", "I have my own room.", "形容詞"),
    "other": ("其他的", "The other students are outside.", "形容詞"),
    "old": ("舊的、老的", "This is an old building.", "形容詞"),
    "right": ("正確的", "You made the right choice.", "形容詞"),
    "big": ("大的", "That's a big elephant.", "形容詞"),
    "high": ("高的", "The mountain is very high.", "形容詞"),
    "small": ("小的", "This shirt is too small.", "形容詞"),
    "large": ("大的", "We need a large pizza.", "形容詞"),
    "next": ("下一個的", "See you next week.", "形容詞"),
    "early": ("早的", "I wake up early every day.", "形容詞"),
    "young": ("年輕的", "She looks very young.", "形容詞"),
    "important": ("重要的", "This is an important message.", "形容詞"),
    "few": ("少數的", "Only a few people came.", "形容詞"),
    "public": ("公共的", "This is a public park.", "形容詞"),
    "bad": ("壞的", "Bad weather is coming.", "形容詞"),
    "same": ("相同的", "We have the same birthday.", "形容詞"),
    "able": ("能夠的", "She is able to swim.", "形容詞"),
    "different": ("不同的", "We have different opinions.", "形容詞"),
    "ready": ("準備好的", "Are you ready to go?", "形容詞"),
    "sure": ("確定的", "I'm sure about this.", "形容詞"),
    "clear": ("清楚的", "The instructions are clear.", "形容詞"),
    "hot": ("熱的", "The weather is hot today.", "形容詞"),
    "cold": ("冷的", "It's cold outside.", "形容詞"),
    "happy": ("快樂的", "I'm happy to see you.", "形容詞"),
    "sad": ("悲傷的", "Don't be sad.", "形容詞"),
    "beautiful": ("美麗的", "The sunset is beautiful.", "形容詞"),
    "nice": ("好的、美好的", "Have a nice day!", "形容詞"),
    "free": ("自由的、免費的", "The concert is free.", "形容詞"),
    "simple": ("簡單的", "This is a simple question.", "形容詞"),
    "difficult": ("困難的", "The test was difficult.", "形容詞"),
    "hard": ("困難的、硬的", "This is a hard problem.", "形容詞"),
    "easy": ("容易的", "The homework is easy.", "形容詞"),
    "fast": ("快的", "He is a fast runner.", "形容詞"),
    "slow": ("慢的", "The turtle is slow.", "形容詞"),
    "strong": ("強壯的", "He is very strong.", "形容詞"),
    "weak": ("虛弱的", "I feel weak today.", "形容詞"),
    "full": ("滿的", "The bus is full.", "形容詞"),
    "empty": ("空的", "The bottle is empty.", "形容詞"),
    "clean": ("乾淨的", "Keep your room clean.", "形容詞"),
    "dirty": ("髒的", "Your shoes are dirty.", "形容詞"),
    "rich": ("富有的", "He comes from a rich family.", "形容詞"),
    "poor": ("貧窮的", "They help poor people.", "形容詞"),
    "special": ("特別的", "This is a special occasion.", "形容詞"),
    "popular": ("受歡迎的", "This song is very popular.", "形容詞"),
    "famous": ("著名的", "He is a famous actor.", "形容詞"),
    "dangerous": ("危險的", "That road is dangerous.", "形容詞"),
    "safe": ("安全的", "This area is safe.", "形容詞"),
    "comfortable": ("舒適的", "This chair is comfortable.", "形容詞"),
    "interesting": ("有趣的", "The book is interesting.", "形容詞"),
    "boring": ("無聊的", "The movie was boring.", "形容詞"),
    "expensive": ("昂貴的", "This car is expensive.", "形容詞"),
    "cheap": ("便宜的", "I bought cheap vegetables.", "形容詞"),
    "bright": ("明亮的", "The sun is bright today.", "形容詞"),
    "dark": ("黑暗的", "The room is dark.", "形容詞"),
    "quiet": ("安靜的", "Please be quiet in the library.", "形容詞"),
    "loud": ("大聲的", "The music is too loud.", "形容詞"),
    "wide": ("寬的", "This is a wide road.", "形容詞"),
    "narrow": ("窄的", "The alley is narrow.", "形容詞"),
    "thick": ("厚的", "This is a thick book.", "形容詞"),
    "thin": ("薄的、瘦的", "The paper is thin.", "形容詞"),
    "fat": ("胖的", "The cat is getting fat.", "形容詞"),
    "tall": ("高的", "He is very tall.", "形容詞"),
    "short": ("矮的、短的", "She has short hair.", "形容詞"),
    "wet": ("濕的", "Your clothes are wet.", "形容詞"),
    "dry": ("乾的", "The towel is dry.", "形容詞"),
    "modern": ("現代的", "This is a modern building.", "形容詞"),
    "ancient": ("古代的", "These are ancient ruins.", "形容詞"),
    "fresh": ("新鮮的", "I like fresh fruit.", "形容詞"),
    "useful": ("有用的", "This tool is useful.", "形容詞"),
    "useless": ("無用的", "This information is useless.", "形容詞"),
    "perfect": ("完美的", "Your answer is perfect.", "形容詞"),
    "correct": ("正確的", "That is the correct answer.", "形容詞"),
    "wrong": ("錯誤的", "Your answer is wrong.", "形容詞"),
    "true": ("真實的", "Is this story true?", "形容詞"),
    "false": ("虛假的", "That statement is false.", "形容詞"),
    "real": ("真實的", "This is a real diamond.", "形容詞"),
    "possible": ("可能的", "Anything is possible.", "形容詞"),
    "impossible": ("不可能的", "Nothing is impossible.", "形容詞"),
    "strange": ("奇怪的", "That's a strange noise.", "形容詞"),
    "normal": ("正常的", "This is normal behavior.", "形容詞"),
    "serious": ("嚴肅的、嚴重的", "This is a serious problem.", "形容詞"),
    "funny": ("有趣的、滑稽的", "He told a funny joke.", "形容詞"),
    "lovely": ("可愛的", "What a lovely baby!", "形容詞"),
    "awful": ("糟糕的", "The weather is awful today.", "形容詞"),
    "terrible": ("可怕的", "That was a terrible accident.", "形容詞"),
    "wonderful": ("精彩的", "We had a wonderful time.", "形容詞"),
    "excellent": ("優秀的", "Your work is excellent.", "形容詞"),
    "poor": ("可憐的、差的", "The poor dog is hungry.", "形容詞"),
    "smart": ("聰明的", "She is a smart student.", "形容詞"),
    "stupid": ("愚蠢的", "That was a stupid mistake.", "形容詞"),
    "clever": ("聰明的", "That's a clever solution.", "形容詞"),
    "silly": ("愚蠢的、傻的", "Don't be silly!", "形容詞"),
    "lazy": ("懶惰的", "He is too lazy to study.", "形容詞"),
    "busy": ("忙碌的", "I'm busy right now.", "形容詞"),
    "active": ("活躍的", "She is very active.", "形容詞"),
    "tired": ("疲倦的", "I feel tired after work.", "形容詞"),
    "hungry": ("飢餓的", "I'm hungry. Let's eat.", "形容詞"),
    "thirsty": ("口渴的", "I'm thirsty. I need water.", "形容詞"),
    "sick": ("生病的", "She feels sick today.", "形容詞"),
    "healthy": ("健康的", "Eating fruit keeps you healthy.", "形容詞"),
    "angry": ("生氣的", "Don't be angry with me.", "形容詞"),
    "afraid": ("害怕的", "I'm afraid of snakes.", "形容詞"),
    "brave": ("勇敢的", "The firefighter is brave.", "形容詞"),
    "careful": ("小心的", "Be careful on the stairs.", "形容詞"),
    "careless": ("粗心的", "That was a careless mistake.", "形容詞"),
    "polite": ("有禮貌的", "He is always polite.", "形容詞"),
    "rude": ("粗魯的", "Don't be rude to others.", "形容詞"),
    "kind": ("善良的", "She is a kind person.", "形容詞"),
    "cruel": ("殘忍的", "Don't be cruel to animals.", "形容詞"),
    "gentle": ("溫柔的", "Be gentle with the baby.", "形容詞"),
    "rough": ("粗糙的", "The surface is rough.", "形容詞"),
    "soft": ("柔軟的", "This pillow is soft.", "形容詞"),
    "smooth": ("平滑的", "The table is smooth.", "形容詞"),
    "sharp": ("鋒利的", "Be careful, the knife is sharp.", "形容詞"),
    "dull": ("鈍的", "This pencil is dull.", "形容詞"),

    # Adverbs
    "very": ("非常", "She is very smart.", "副詞"),
    "also": ("也", "I also like pizza.", "副詞"),
    "well": ("好地", "She dances well.", "副詞"),
    "only": ("只、僅", "I only have one pen.", "副詞"),
    "just": ("剛才、只是", "I just arrived home.", "副詞"),
    "now": ("現在", "We must go now.", "副詞"),
    "back": ("回來", "Come back soon.", "副詞"),
    "then": ("然後", "We ate dinner, then watched TV.", "副詞"),
    "still": ("仍然", "She is still sleeping.", "副詞"),
    "even": ("甚至", "Even children can do this.", "副詞"),
    "much": ("很多", "Thank you very much.", "副詞"),
    "really": ("真的", "I really like you.", "副詞"),
    "never": ("從不", "I never lie.", "副詞"),
    "always": ("總是", "She always arrives on time.", "副詞"),
    "often": ("經常", "I often go to the park.", "副詞"),
    "sometimes": ("有時", "Sometimes I feel lonely.", "副詞"),
    "usually": ("通常", "I usually wake up at 7.", "副詞"),
    "already": ("已經", "I already finished my homework.", "副詞"),
    "almost": ("幾乎", "We're almost there.", "副詞"),
    "together": ("一起", "Let's work together.", "副詞"),
    "today": ("今天", "Today is Monday.", "副詞"),
    "yesterday": ("昨天", "I saw him yesterday.", "副詞"),
    "tomorrow": ("明天", "See you tomorrow.", "副詞"),
    "here": ("這裡", "Come here please.", "副詞"),
    "there": ("那裡", "Put it there.", "副詞"),
    "everywhere": ("到處", "I looked everywhere for my keys.", "副詞"),
    "nowhere": ("無處", "There's nowhere to hide.", "副詞"),
    "somewhere": ("某處", "He must be somewhere nearby.", "副詞"),
    "perhaps": ("也許", "Perhaps we should wait.", "副詞"),
    "maybe": ("也許", "Maybe it will rain.", "副詞"),
    "probably": ("可能", "She will probably come.", "副詞"),
    "certainly": ("當然", "I will certainly help you.", "副詞"),
    "exactly": ("確切地", "That's exactly right.", "副詞"),
    "especially": ("特別", "I love fruit, especially apples.", "副詞"),
    "quickly": ("快速地", "Run quickly!", "副詞"),
    "slowly": ("慢慢地", "Please speak slowly.", "副詞"),
    "carefully": ("小心地", "Drive carefully.", "副詞"),
    "suddenly": ("突然", "Suddenly, the lights went out.", "副詞"),
    "finally": ("最後", "Finally, we arrived home.", "副詞"),
    "recently": ("最近", "I recently started jogging.", "副詞"),
    "immediately": ("立刻", "Come here immediately.", "副詞"),
    "directly": ("直接地", "Go directly to school.", "副詞"),
    "completely": ("完全地", "I completely agree.", "副詞"),
    "extremely": ("極其", "The weather is extremely hot.", "副詞"),
    "nearly": ("幾乎", "It's nearly midnight.", "副詞"),
    "hardly": ("幾乎不", "I can hardly wait.", "副詞"),
    "clearly": ("清楚地", "I can see clearly now.", "副詞"),
    "easily": ("容易地", "She solved it easily.", "副詞"),
    "simply": ("簡單地", "Simply follow the instructions.", "副詞"),
    "actually": ("實際上", "Actually, I don't know.", "副詞"),
    "naturally": ("自然地", "She sings naturally.", "副詞"),
    "basically": ("基本上", "Basically, we agree.", "副詞"),
    "unfortunately": ("不幸地", "Unfortunately, he was late.", "副詞"),
    "luckily": ("幸運地", "Luckily, no one was hurt.", "副詞"),
    "hopefully": ("希望", "Hopefully, the weather improves.", "副詞"),
    "seriously": ("認真地", "Take this seriously.", "副詞"),
    "honestly": ("誠實地", "Honestly, I don't know.", "副詞"),
    "quietly": ("安靜地", "Please walk quietly.", "副詞"),
    "loudly": ("大聲地", "Don't speak loudly in class.", "副詞"),
    "happily": ("快樂地", "They lived happily ever after.", "副詞"),
    "sadly": ("悲傷地", "Sadly, he passed away.", "副詞"),
    "badly": ("嚴重地、糟糕地", "He was badly injured.", "副詞"),
    "partly": ("部分地", "You're partly right.", "副詞"),
    "mostly": ("主要地", "I mostly eat vegetables.", "副詞"),
    "mainly": ("主要地", "This is mainly for students.", "副詞"),
    "forward": ("向前", "Move forward please.", "副詞"),
    "backward": ("向後", "Don't look backward.", "副詞"),
    "upward": ("向上", "Look upward at the stars.", "副詞"),
    "downward": ("向下", "The arrow points downward.", "副詞"),
    "inside": ("在裡面", "Come inside quickly.", "副詞"),
    "outside": ("在外面", "Let's play outside.", "副詞"),
    "upstairs": ("在樓上", "My room is upstairs.", "副詞"),
    "downstairs": ("在樓下", "The kitchen is downstairs.", "副詞"),
    "abroad": ("在國外", "She studies abroad.", "副詞"),
    "away": ("離開", "Go away!", "副詞"),
    "apart": ("分開地", "They live far apart.", "副詞"),
    "aside": ("在旁邊", "Step aside please.", "副詞"),
    "ahead": ("在前面", "Go straight ahead.", "副詞"),
    "behind": ("在後面", "Don't leave anyone behind.", "副詞"),
    "nearby": ("在附近", "There's a store nearby.", "副詞"),
    "far": ("遠", "Don't go too far.", "副詞"),
    "close": ("接近", "Come close to me.", "副詞"),
    "late": ("晚", "Don't arrive late.", "副詞"),
    "soon": ("很快", "I'll be there soon.", "副詞"),
    "early": ("早", "I woke up early today.", "副詞"),
    "ago": ("以前", "I met him years ago.", "副詞"),
    "before": ("以前", "I've seen this before.", "副詞"),
    "after": ("之後", "We'll talk after class.", "副詞"),
    "yet": ("還", "I haven't eaten yet.", "副詞"),
    "once": ("曾經、一次", "I visited once.", "副詞"),
    "twice": ("兩次", "I called twice.", "副詞"),
    "again": ("再次", "Please say that again.", "副詞"),
    "forever": ("永遠", "I'll remember this forever.", "副詞"),
    "meanwhile": ("同時", "Meanwhile, I'll prepare lunch.", "副詞"),
    "otherwise": ("否則", "Hurry, otherwise we'll be late.", "副詞"),
    "therefore": ("因此", "Therefore, we must leave now.", "副詞"),
    "however": ("然而", "However, there's a problem.", "副詞"),
    "indeed": ("的確", "That is indeed correct.", "副詞"),
    "besides": ("此外", "Besides, I'm too tired.", "副詞"),
    "moreover": ("而且", "Moreover, it's too expensive.", "副詞"),
    "furthermore": ("此外", "Furthermore, we have no time.", "副詞"),
    "nevertheless": ("然而", "Nevertheless, we should try.", "副詞"),
    "thus": ("因此", "Thus, we reached our goal.", "副詞"),
    "hence": ("因此", "Hence, the conclusion is clear.", "副詞"),
    "accordingly": ("因此", "Accordingly, we changed plans.", "副詞"),

    # Advanced nouns - common -tion/-sion words
    "compensation": ("補償、賠償", "Workers deserve fair compensation for their labor.", "名詞"),
    "conclusion": ("結論", "We reached an important conclusion after much discussion.", "名詞"),
    "configuration": ("配置、設定", "The system configuration needs to be updated.", "名詞"),
    "confirmation": ("確認", "We're waiting for confirmation of the appointment.", "名詞"),
    "consideration": ("考慮", "Price is an important consideration when buying.", "名詞"),
    "consumption": ("消費、消耗", "Energy consumption has increased this year.", "名詞"),
    "conversation": ("對話、會話", "We had an interesting conversation about history.", "名詞"),
    "description": ("描述", "Please provide a detailed description of the problem.", "名詞"),
    "destruction": ("破壞", "The earthquake caused widespread destruction.", "名詞"),
    "determination": ("決心", "Her determination helped her succeed.", "名詞"),
    "discretion": ("判斷力、謹慎", "Use your discretion in this matter.", "名詞"),
    "distinction": ("區別、卓越", "There's a clear distinction between the two concepts.", "名詞"),
    "frustration": ("挫折、沮喪", "He felt frustration after failing the test.", "名詞"),
    "incorporation": ("合併、納入", "The incorporation of new ideas improved the project.", "名詞"),
    "injunction": ("禁令", "The court issued an injunction to stop the work.", "名詞"),
    "inspection": ("檢查", "The building passed the safety inspection.", "名詞"),
    "instruction": ("指示、教學", "Follow the instructions carefully.", "名詞"),
    "intervention": ("干預、介入", "Early intervention can prevent problems.", "名詞"),
    "jurisdiction": ("管轄權", "This case falls under federal jurisdiction.", "名詞"),
    "justification": ("理由、辯護", "There's no justification for such behavior.", "名詞"),
    "information": ("資訊", "We need more information.", "名詞"),
    "education": ("教育", "Education is the key to success.", "名詞"),
    "communication": ("溝通", "Good communication is essential.", "名詞"),
    "organization": ("組織", "The organization helps poor families.", "名詞"),
    "population": ("人口", "The population is growing rapidly.", "名詞"),
    "situation": ("情況", "The situation is getting better.", "名詞"),
    "attention": ("注意", "Pay attention in class.", "名詞"),
    "direction": ("方向", "Follow the direction signs.", "名詞"),
    "position": ("位置、職位", "I applied for a teaching position.", "名詞"),
    "condition": ("狀況、條件", "The car is in good condition.", "名詞"),
    "decision": ("決定", "Making decisions can be difficult.", "名詞"),
    "action": ("行動", "We must take action now.", "名詞"),
    "reaction": ("反應", "What was her reaction to the news?", "名詞"),
    "protection": ("保護", "Children need protection from harm.", "名詞"),
    "production": ("生產", "Production has increased this month.", "名詞"),
    "reduction": ("減少", "We need a reduction in costs.", "名詞"),
    "connection": ("連接", "There's a connection between these events.", "名詞"),
    "collection": ("收集", "He has a large stamp collection.", "名詞"),
    "selection": ("選擇", "The store has a good selection of books.", "名詞"),
    "election": ("選舉", "The election will be held next month.", "名詞"),
    "reflection": ("反映、反思", "This is a reflection of our values.", "名詞"),
    "infection": ("感染", "The wound showed signs of infection.", "名詞"),
    "section": ("部分、區域", "Read the first section of the chapter.", "名詞"),
    "function": ("功能", "What is the function of this button?", "名詞"),
    "construction": ("建設、建造", "The construction will take six months.", "名詞"),
    "discussion": ("討論", "We had a long discussion about the plan.", "名詞"),
    "permission": ("許可", "You need permission to enter.", "名詞"),
    "admission": ("入場、承認", "Admission to the museum is free.", "名詞"),
    "mission": ("任務、使命", "Their mission is to help others.", "名詞"),
    "profession": ("職業", "Teaching is a noble profession.", "名詞"),
    "expression": ("表達、表情", "She had a sad expression on her face.", "名詞"),
    "impression": ("印象", "First impressions are important.", "名詞"),
    "depression": ("憂鬱、蕭條", "The country faced economic depression.", "名詞"),
    "session": ("會議、時段", "The training session lasts two hours.", "名詞"),
    "passion": ("熱情", "She has a passion for music.", "名詞"),
    "version": ("版本", "Download the latest version of the software.", "名詞"),
    "division": ("分割、部門", "He works in the marketing division.", "名詞"),
    "vision": ("視力、遠見", "She has excellent vision.", "名詞"),
    "decision": ("決定", "It was a difficult decision to make.", "名詞"),
    "occasion": ("場合、時機", "This is a special occasion.", "名詞"),
    "conclusion": ("結論", "What conclusion did you reach?", "名詞"),
    "confusion": ("困惑", "There was confusion about the schedule.", "名詞"),

    # Advanced nouns - other patterns
    "assessment": ("評估", "The assessment showed positive results.", "名詞"),
    "development": ("發展", "Child development requires good nutrition.", "名詞"),
    "environment": ("環境", "We must protect the environment.", "名詞"),
    "government": ("政府", "The government makes laws.", "名詞"),
    "movement": ("運動、移動", "The civil rights movement changed history.", "名詞"),
    "improvement": ("改善", "We've seen great improvement in his work.", "名詞"),
    "achievement": ("成就", "Graduating is a great achievement.", "名詞"),
    "agreement": ("協議", "We reached an agreement after negotiation.", "名詞"),
    "arrangement": ("安排", "The seating arrangement is perfect.", "名詞"),
    "treatment": ("治療、對待", "The medical treatment was successful.", "名詞"),
    "statement": ("聲明、陳述", "The company issued an official statement.", "名詞"),
    "measurement": ("測量", "Take careful measurements before cutting.", "名詞"),
    "equipment": ("設備", "The laboratory has modern equipment.", "名詞"),
    "requirement": ("要求", "Meeting the requirements is essential.", "名詞"),
    "employment": ("就業", "Employment rates are rising.", "名詞"),
    "entertainment": ("娛樂", "The city offers plenty of entertainment.", "名詞"),
    "argument": ("爭論、論點", "They had a heated argument.", "名詞"),
    "department": ("部門", "She works in the sales department.", "名詞"),
    "apartment": ("公寓", "They live in a small apartment.", "名詞"),
    "document": ("文件", "Please sign this document.", "名詞"),
    "moment": ("時刻", "Wait just a moment please.", "名詞"),
    "comment": ("評論", "Do you have any comments?", "名詞"),
    "payment": ("付款", "Payment is due by Friday.", "名詞"),
    "investment": ("投資", "Education is a good investment.", "名詞"),
    "experiment": ("實驗", "The science experiment was successful.", "名詞"),
    "replacement": ("替換", "We need a replacement for the broken part.", "名詞"),
    "management": ("管理", "Good management is crucial for success.", "名詞"),
    "establishment": ("建立、機構", "The establishment of new rules was necessary.", "名詞"),

    # Advanced adjectives
    "traditional": ("傳統的", "This is a traditional Chinese festival.", "形容詞"),
    "national": ("國家的", "National security is a priority.", "形容詞"),
    "international": ("國際的", "This is an international organization.", "形容詞"),
    "professional": ("專業的", "She provides professional service.", "形容詞"),
    "personal": ("個人的", "This is my personal opinion.", "形容詞"),
    "natural": ("自然的", "Use only natural ingredients.", "形容詞"),
    "equal": ("平等的", "All people are equal.", "形容詞"),
    "local": ("當地的", "Support local businesses.", "形容詞"),
    "global": ("全球的", "Climate change is a global issue.", "形容詞"),
    "final": ("最終的", "This is my final answer.", "形容詞"),
    "original": ("原始的、獨創的", "That's a very original idea.", "形容詞"),
    "general": ("一般的", "As a general rule, arrive early.", "形容詞"),
    "social": ("社會的", "Social media is very popular.", "形容詞"),
    "special": ("特別的", "This is a special occasion.", "形容詞"),
    "central": ("中心的", "The park is in a central location.", "形容詞"),
    "medical": ("醫學的", "He needs medical attention.", "形容詞"),
    "physical": ("物理的、身體的", "Regular physical exercise is important.", "形容詞"),
    "mental": ("心理的", "Mental health matters.", "形容詞"),
    "financial": ("財務的", "We face financial difficulties.", "形容詞"),
    "commercial": ("商業的", "This is a commercial building.", "形容詞"),
    "industrial": ("工業的", "The industrial revolution changed the world.", "形容詞"),
    "cultural": ("文化的", "This is a cultural tradition.", "形容詞"),
    "political": ("政治的", "Political debates can be intense.", "形容詞"),
    "critical": ("批判的、關鍵的", "This is a critical moment.", "形容詞"),
    "typical": ("典型的", "This is typical behavior for children.", "形容詞"),
    "practical": ("實用的", "That's a very practical solution.", "形容詞"),
    "technical": ("技術的", "This requires technical knowledge.", "形容詞"),
    "historical": ("歷史的", "This is a historical building.", "形容詞"),
    "electrical": ("電氣的", "Check the electrical connections.", "形容詞"),
    "chemical": ("化學的", "Avoid chemical cleaners.", "形容詞"),
    "digital": ("數位的", "We live in a digital age.", "形容詞"),
    "individual": ("個別的", "Each individual case is different.", "形容詞"),
    "additional": ("額外的", "No additional fees apply.", "形容詞"),
    "environmental": ("環境的", "Environmental protection is important.", "形容詞"),
    "educational": ("教育的", "This is an educational program.", "形容詞"),

    # Advanced verbs
    "access": ("使用、存取", "You can access the files online.", "動詞"),
    "assess": ("評估", "We need to assess the situation.", "動詞"),
    "address": ("處理、演說", "We must address this problem.", "動詞"),
    "achieve": ("達成", "You can achieve your goals.", "動詞"),
    "develop": ("發展", "They develop new software.", "動詞"),
    "establish": ("建立", "We need to establish rules.", "動詞"),
    "maintain": ("維持", "Please maintain silence.", "動詞"),
    "obtain": ("獲得", "You must obtain permission first.", "動詞"),
    "occur": ("發生", "Accidents can occur anywhere.", "動詞"),
    "provide": ("提供", "We provide quality service.", "動詞"),
    "receive": ("收到", "Did you receive my message?", "動詞"),
    "reduce": ("減少", "We should reduce waste.", "動詞"),
    "represent": ("代表", "I represent my school.", "動詞"),
    "respond": ("回應", "Please respond to the email.", "動詞"),
    "support": ("支持", "We support this initiative.", "動詞"),
    "involve": ("涉及、包含", "This job involves travel.", "動詞"),
    "improve": ("改善", "We can improve our skills.", "動詞"),
    "increase": ("增加", "Prices will increase next month.", "動詞"),
    "require": ("需要", "This job requires patience.", "動詞"),
    "arrange": ("安排", "I'll arrange a meeting.", "動詞"),
    "compare": ("比較", "Compare these two products.", "動詞"),
    "complete": ("完成", "Please complete the form.", "動詞"),
    "describe": ("描述", "Can you describe the person?", "動詞"),
    "determine": ("決定", "Tests determine your level.", "動詞"),
    "examine": ("檢查", "The doctor will examine you.", "動詞"),
    "explain": ("解釋", "Let me explain the rules.", "動詞"),
    "express": ("表達", "Express your feelings honestly.", "動詞"),
    "identify": ("識別", "Can you identify this plant?", "動詞"),
    "indicate": ("指出", "Results indicate improvement.", "動詞"),
    "manage": ("管理", "She manages the team well.", "動詞"),
    "measure": ("測量", "Measure the distance carefully.", "動詞"),
    "operate": ("操作", "Do you know how to operate this machine?", "動詞"),
    "organize": ("組織", "We should organize our files.", "動詞"),
    "prepare": ("準備", "I'll prepare dinner tonight.", "動詞"),
    "replace": ("替換", "We need to replace the battery.", "動詞"),
    "separate": ("分開", "Separate the colors from whites.", "動詞"),

    # More common words students should know
    "current": ("當前的、水流", "The current situation is improving.", "形容詞"),
    "protect": ("保護", "We must protect the environment.", "動詞"),
    "govern": ("統治、管理", "Laws govern our society.", "動詞"),
    "discover": ("發現", "Scientists discover new things daily.", "動詞"),
    "appear": ("出現", "Stars appear at night.", "動詞"),
    "contain": ("包含", "This box contains old photos.", "動詞"),
    "perform": ("表演、執行", "She will perform on stage tonight.", "動詞"),
    "realize": ("意識到", "I didn't realize the time.", "動詞"),
    "recognize": ("認出", "I can recognize her voice.", "動詞"),
    "remember": ("記得", "I remember your name.", "動詞"),
    "forget": ("忘記", "Don't forget your homework.", "動詞"),
    "discuss": ("討論", "Let's discuss this matter.", "動詞"),
    "announce": ("宣布", "They will announce the winner soon.", "動詞"),
    "apply": ("申請、應用", "I will apply for the job.", "動詞"),
    "belong": ("屬於", "This book belongs to me.", "動詞"),
    "consist": ("組成", "The team consists of five members.", "動詞"),
    "depend": ("依靠", "Success depends on hard work.", "動詞"),
    "destroy": ("破壞", "Fire can destroy forests.", "動詞"),
    "disappear": ("消失", "The sun will disappear behind clouds.", "動詞"),
    "doubt": ("懷疑", "I doubt that story is true.", "動詞"),
    "enable": ("使能夠", "This app enables easy communication.", "動詞"),
    "encourage": ("鼓勵", "Teachers encourage students to try.", "動詞"),
    "ensure": ("確保", "Please ensure all doors are locked.", "動詞"),
    "exist": ("存在", "Do ghosts really exist?", "動詞"),
    "explore": ("探索", "Let's explore the forest.", "動詞"),
    "gather": ("聚集", "We gather every Sunday.", "動詞"),
    "imagine": ("想像", "Imagine a world without war.", "動詞"),
    "impress": ("使印象深刻", "Her skills impress everyone.", "動詞"),
    "intend": ("打算", "I intend to study abroad.", "動詞"),
    "invent": ("發明", "Who invented the telephone?", "動詞"),
    "investigate": ("調查", "Police will investigate the crime.", "動詞"),
    "mention": ("提到", "Did I mention the meeting?", "動詞"),
    "notice": ("注意到", "Did you notice anything strange?", "動詞"),
    "predict": ("預測", "Nobody can predict the future.", "動詞"),
    "prefer": ("偏好", "I prefer tea to coffee.", "動詞"),
    "present": ("呈現、贈送", "Let me present my idea.", "動詞"),
    "prevent": ("防止", "Exercise prevents disease.", "動詞"),
    "promise": ("承諾", "I promise to help you.", "動詞"),
    "refuse": ("拒絕", "She refused to answer.", "動詞"),
    "regret": ("後悔", "I regret my decision.", "動詞"),
    "relate": ("關聯", "This story relates to history.", "動詞"),
    "relax": ("放鬆", "You should relax more.", "動詞"),
    "remove": ("移除", "Please remove your shoes.", "動詞"),
    "repeat": ("重複", "Please repeat the question.", "動詞"),
    "request": ("請求", "I request your assistance.", "動詞"),
    "respect": ("尊重", "We should respect others.", "動詞"),
    "reveal": ("揭露", "The test will reveal the truth.", "動詞"),
    "satisfy": ("滿足", "This answer satisfies me.", "動詞"),
    "select": ("選擇", "Please select one option.", "動詞"),
    "serve": ("服務", "Waiters serve food.", "動詞"),
    "settle": ("定居、解決", "They settled in a new city.", "動詞"),
    "suffer": ("遭受", "Many people suffer from stress.", "動詞"),
    "suppose": ("假設", "I suppose you're right.", "動詞"),
    "surprise": ("使驚訝", "The news will surprise you.", "動詞"),
    "survive": ("存活", "Plants can't survive without water.", "動詞"),
    "threaten": ("威脅", "Don't threaten me.", "動詞"),
    "trust": ("信任", "I trust you completely.", "動詞"),
    "unite": ("聯合", "We must unite together.", "動詞"),
    "warn": ("警告", "I warn you to be careful.", "動詞"),
    "wonder": ("想知道", "I wonder where she is.", "動詞"),
    "worry": ("擔心", "Don't worry about it.", "動詞"),

    # More common nouns
    "ability": ("能力", "She has great musical ability.", "名詞"),
    "accident": ("意外", "There was a car accident.", "名詞"),
    "activity": ("活動", "Swimming is my favorite activity.", "名詞"),
    "advantage": ("優勢", "Experience is an advantage.", "名詞"),
    "advice": ("建議", "Can you give me some advice?", "名詞"),
    "amount": ("數量", "A large amount of water is needed.", "名詞"),
    "anger": ("憤怒", "His anger was obvious.", "名詞"),
    "appearance": ("外表", "Don't judge by appearance.", "名詞"),
    "article": ("文章", "I read an interesting article.", "名詞"),
    "attitude": ("態度", "A positive attitude helps.", "名詞"),
    "audience": ("觀眾", "The audience applauded loudly.", "名詞"),
    "authority": ("權威、當局", "Respect authority figures.", "名詞"),
    "background": ("背景", "Tell me your background.", "名詞"),
    "balance": ("平衡", "Maintain a work-life balance.", "名詞"),
    "basis": ("基礎", "Trust is the basis of friendship.", "名詞"),
    "battle": ("戰鬥", "The battle lasted all night.", "名詞"),
    "beauty": ("美麗", "Beauty comes from within.", "名詞"),
    "behavior": ("行為", "Good behavior is important.", "名詞"),
    "belief": ("信念", "Everyone has different beliefs.", "名詞"),
    "benefit": ("利益", "Exercise has many benefits.", "名詞"),
    "cancer": ("癌症", "Cancer research saves lives.", "名詞"),
    "capacity": ("容量、能力", "The hall has a large capacity.", "名詞"),
    "career": ("職業生涯", "She has a successful career.", "名詞"),
    "category": ("類別", "Put items in the correct category.", "名詞"),
    "cause": ("原因", "What was the cause of the fire?", "名詞"),
    "century": ("世紀", "We live in the 21st century.", "名詞"),
    "challenge": ("挑戰", "This is a difficult challenge.", "名詞"),
    "chance": ("機會", "Give me another chance.", "名詞"),
    "character": ("性格、角色", "She has a strong character.", "名詞"),
    "choice": ("選擇", "You made a good choice.", "名詞"),
    "circumstance": ("情況", "Under the circumstances, we agreed.", "名詞"),
    "citizen": ("公民", "Every citizen has rights.", "名詞"),
    "climate": ("氣候", "The climate is changing.", "名詞"),
    "college": ("學院", "She goes to college.", "名詞"),
    "combination": ("組合", "This is a good combination.", "名詞"),
    "committee": ("委員會", "The committee meets monthly.", "名詞"),
    "competition": ("競爭", "The competition was fierce.", "名詞"),
    "computer": ("電腦", "I use my computer daily.", "名詞"),
    "concept": ("概念", "Explain the concept clearly.", "名詞"),
    "concern": ("關心、擔憂", "Safety is our main concern.", "名詞"),
    "conflict": ("衝突", "We must resolve this conflict.", "名詞"),
    "congress": ("國會", "Congress passed a new law.", "名詞"),
    "consequence": ("後果", "Every action has consequences.", "名詞"),
    "contact": ("聯絡", "Stay in contact with me.", "名詞"),
    "content": ("內容", "The content is interesting.", "名詞"),
    "context": ("背景、上下文", "Understand the context first.", "名詞"),
    "contract": ("合約", "Sign the contract here.", "名詞"),
    "contrast": ("對比", "Notice the contrast in colors.", "名詞"),
    "control": ("控制", "He lost control of the car.", "名詞"),
    "conversation": ("對話", "We had a nice conversation.", "名詞"),
    "courage": ("勇氣", "It takes courage to change.", "名詞"),
    "course": ("課程", "I'm taking an English course.", "名詞"),
    "crime": ("犯罪", "Crime rates are falling.", "名詞"),
    "crisis": ("危機", "We face an economic crisis.", "名詞"),
    "culture": ("文化", "Every country has unique culture.", "名詞"),
    "customer": ("顧客", "The customer is always right.", "名詞"),
    "damage": ("損害", "The storm caused damage.", "名詞"),
    "danger": ("危險", "There's danger ahead.", "名詞"),
    "debate": ("辯論", "The debate was interesting.", "名詞"),
    "decade": ("十年", "A lot changed in one decade.", "名詞"),
    "degree": ("程度、學位", "She has a master's degree.", "名詞"),
    "demand": ("需求", "There's high demand for this product.", "名詞"),
    "democracy": ("民主", "Democracy gives people power.", "名詞"),
    "design": ("設計", "I love this design.", "名詞"),
    "desire": ("渴望", "His desire to win is strong.", "名詞"),
    "detail": ("細節", "Pay attention to every detail.", "名詞"),
    "device": ("裝置", "This device is very useful.", "名詞"),
    "difference": ("差異", "There's a big difference.", "名詞"),
    "difficulty": ("困難", "We face many difficulties.", "名詞"),
    "dinner": ("晚餐", "Join us for dinner.", "名詞"),
    "disease": ("疾病", "This disease is contagious.", "名詞"),
    "distance": ("距離", "The distance is too far.", "名詞"),
    "doubt": ("懷疑", "I have no doubt about it.", "名詞"),
    "dream": ("夢想", "Follow your dreams.", "名詞"),
    "duty": ("職責", "It's my duty to help.", "名詞"),
    "economy": ("經濟", "The economy is growing.", "名詞"),
    "edge": ("邊緣", "Don't stand near the edge.", "名詞"),
    "effect": ("效果", "The medicine had no effect.", "名詞"),
    "effort": ("努力", "Your effort is appreciated.", "名詞"),
    "emotion": ("情感", "She showed no emotion.", "名詞"),
    "employee": ("員工", "Every employee gets benefits.", "名詞"),
    "enemy": ("敵人", "They became enemies.", "名詞"),
    "energy": ("能量", "I have no energy left.", "名詞"),
    "engineer": ("工程師", "He's a software engineer.", "名詞"),
    "error": ("錯誤", "There's an error in the calculation.", "名詞"),
    "evidence": ("證據", "The evidence is clear.", "名詞"),
    "example": ("例子", "This is a good example.", "名詞"),
    "exchange": ("交換", "We did a student exchange.", "名詞"),
    "exercise": ("運動", "Daily exercise is important.", "名詞"),
    "experience": ("經驗", "I lack work experience.", "名詞"),
    "explosion": ("爆炸", "The explosion was loud.", "名詞"),
    "feature": ("特徵", "This phone has many features.", "名詞"),
    "figure": ("數字、人物", "The figure shows growth.", "名詞"),
    "force": ("力量", "Don't use force.", "名詞"),
    "freedom": ("自由", "Freedom is precious.", "名詞"),
    "future": ("未來", "The future looks bright.", "名詞"),
    "goal": ("目標", "Set realistic goals.", "名詞"),
    "growth": ("成長", "Economic growth is steady.", "名詞"),
    "habit": ("習慣", "Reading is a good habit.", "名詞"),
    "hospital": ("醫院", "She works at a hospital.", "名詞"),
    "hotel": ("旅館", "We stayed at a nice hotel.", "名詞"),
    "image": ("影像", "The image is unclear.", "名詞"),
    "impact": ("影響", "Technology has great impact.", "名詞"),
    "industry": ("工業", "The car industry is huge.", "名詞"),
    "influence": ("影響力", "Parents have strong influence.", "名詞"),
    "injury": ("傷害", "He suffered a serious injury.", "名詞"),
    "instance": ("例子", "For instance, look at this.", "名詞"),
    "interest": ("興趣", "What are your interests?", "名詞"),
    "introduction": ("介紹", "Let me make an introduction.", "名詞"),
    "issue": ("議題", "This is an important issue.", "名詞"),
    "item": ("項目", "Check each item carefully.", "名詞"),
    "journey": ("旅程", "Life is a journey.", "名詞"),
    "knowledge": ("知識", "Knowledge is power.", "名詞"),
    "language": ("語言", "English is a global language.", "名詞"),
    "leader": ("領導者", "Every team needs a leader.", "名詞"),
    "length": ("長度", "Measure the length carefully.", "名詞"),
    "library": ("圖書館", "I study at the library.", "名詞"),
    "limit": ("限制", "There's no age limit.", "名詞"),
    "loss": ("損失", "The company suffered losses.", "名詞"),
    "marriage": ("婚姻", "Marriage requires commitment.", "名詞"),
    "material": ("材料", "We need building materials.", "名詞"),
    "matter": ("事情", "This is a serious matter.", "名詞"),
    "meaning": ("意義", "What's the meaning of this word?", "名詞"),
    "measure": ("測量、措施", "Take preventive measures.", "名詞"),
    "memory": ("記憶", "I have a good memory.", "名詞"),
    "method": ("方法", "This is an effective method.", "名詞"),
    "model": ("模型、模範", "She's a fashion model.", "名詞"),
    "nature": ("自然", "I love spending time in nature.", "名詞"),
    "network": ("網路", "Build your professional network.", "名詞"),
    "object": ("物體", "What is that strange object?", "名詞"),
    "opinion": ("意見", "Everyone has an opinion.", "名詞"),
    "opportunity": ("機會", "This is a great opportunity.", "名詞"),
    "option": ("選項", "You have several options.", "名詞"),
    "order": ("命令、順序", "Follow the orders carefully.", "名詞"),
    "pain": ("疼痛", "I feel pain in my back.", "名詞"),
    "pattern": ("模式", "I notice a pattern here.", "名詞"),
    "period": ("時期", "This was a difficult period.", "名詞"),
    "pleasure": ("快樂", "It's my pleasure to help.", "名詞"),
    "policy": ("政策", "The new policy is effective.", "名詞"),
    "pollution": ("污染", "Air pollution is dangerous.", "名詞"),
    "practice": ("練習", "Practice makes perfect.", "名詞"),
    "pressure": ("壓力", "I feel a lot of pressure.", "名詞"),
    "pride": ("驕傲", "Take pride in your work.", "名詞"),
    "principle": ("原則", "Stick to your principles.", "名詞"),
    "priority": ("優先", "Safety is our top priority.", "名詞"),
    "process": ("過程", "The process takes time.", "名詞"),
    "profit": ("利潤", "The company made a profit.", "名詞"),
    "progress": ("進步", "We're making good progress.", "名詞"),
    "project": ("專案", "We're working on a project.", "名詞"),
    "promise": ("承諾", "Keep your promises.", "名詞"),
    "proof": ("證明", "Show me proof.", "名詞"),
    "property": ("財產", "This is private property.", "名詞"),
    "proposal": ("提案", "The proposal was accepted.", "名詞"),
    "purpose": ("目的", "What's the purpose of this meeting?", "名詞"),
    "quality": ("品質", "Quality is more important than quantity.", "名詞"),
    "quantity": ("數量", "We need a large quantity.", "名詞"),
    "rate": ("比率", "The crime rate is falling.", "名詞"),
    "reality": ("現實", "Face reality.", "名詞"),
    "relationship": ("關係", "Good relationships take work.", "名詞"),
    "religion": ("宗教", "Respect all religions.", "名詞"),
    "reputation": ("聲譽", "Protect your reputation.", "名詞"),
    "research": ("研究", "Scientific research is important.", "名詞"),
    "respect": ("尊重", "Show respect to elders.", "名詞"),
    "responsibility": ("責任", "Take responsibility for your actions.", "名詞"),
    "restaurant": ("餐廳", "This restaurant serves great food.", "名詞"),
    "result": ("結果", "Wait for the test results.", "名詞"),
    "revolution": ("革命", "The industrial revolution changed everything.", "名詞"),
    "risk": ("風險", "Every decision involves risk.", "名詞"),
    "role": ("角色", "Everyone has an important role.", "名詞"),
    "routine": ("常規", "Follow your daily routine.", "名詞"),
    "rule": ("規則", "Follow the rules.", "名詞"),
    "safety": ("安全", "Safety comes first.", "名詞"),
    "scene": ("場景", "The crime scene was secured.", "名詞"),
    "schedule": ("時間表", "Check the schedule.", "名詞"),
    "science": ("科學", "Science explains nature.", "名詞"),
    "season": ("季節", "Summer is my favorite season.", "名詞"),
    "secret": ("秘密", "Can you keep a secret?", "名詞"),
    "security": ("安全", "Airport security is tight.", "名詞"),
    "series": ("系列", "This is a TV series.", "名詞"),
    "shadow": ("影子", "I saw a shadow move.", "名詞"),
    "shape": ("形狀", "The cake is heart-shaped.", "名詞"),
    "signal": ("信號", "Wait for my signal.", "名詞"),
    "silence": ("沉默", "Silence filled the room.", "名詞"),
    "skill": ("技能", "She has excellent computer skills.", "名詞"),
    "solution": ("解決方案", "We found a solution.", "名詞"),
    "source": ("來源", "What's your news source?", "名詞"),
    "space": ("空間", "We need more space.", "名詞"),
    "species": ("物種", "Many species are endangered.", "名詞"),
    "speech": ("演講", "He gave a great speech.", "名詞"),
    "speed": ("速度", "Slow down your speed.", "名詞"),
    "spirit": ("精神", "Team spirit is important.", "名詞"),
    "standard": ("標準", "Meet the quality standards.", "名詞"),
    "star": ("星星", "Look at the stars.", "名詞"),
    "strategy": ("策略", "We need a new strategy.", "名詞"),
    "stress": ("壓力", "Reduce your stress levels.", "名詞"),
    "structure": ("結構", "The building's structure is strong.", "名詞"),
    "struggle": ("掙扎", "The struggle was real.", "名詞"),
    "style": ("風格", "Everyone has their own style.", "名詞"),
    "subject": ("科目、主題", "Math is my favorite subject.", "名詞"),
    "success": ("成功", "Success requires hard work.", "名詞"),
    "sugar": ("糖", "Too much sugar is unhealthy.", "名詞"),
    "surface": ("表面", "The surface is smooth.", "名詞"),
    "survey": ("調查", "Fill out this survey.", "名詞"),
    "symbol": ("符號", "The dove is a symbol of peace.", "名詞"),
    "target": ("目標", "We hit our sales target.", "名詞"),
    "task": ("任務", "Complete each task carefully.", "名詞"),
    "tax": ("稅", "We all pay taxes.", "名詞"),
    "team": ("團隊", "Our team won the game.", "名詞"),
    "temperature": ("溫度", "The temperature is rising.", "名詞"),
    "theory": ("理論", "That's just a theory.", "名詞"),
    "threat": ("威脅", "Climate change is a threat.", "名詞"),
    "title": ("標題", "Give your essay a title.", "名詞"),
    "topic": ("主題", "Choose an interesting topic.", "名詞"),
    "tradition": ("傳統", "Respect family traditions.", "名詞"),
    "traffic": ("交通", "The traffic is terrible today.", "名詞"),
    "trend": ("趨勢", "This is a new trend.", "名詞"),
    "trial": ("審判、試驗", "The trial lasted three weeks.", "名詞"),
    "trouble": ("麻煩", "I'm in trouble.", "名詞"),
    "truth": ("真理", "Always tell the truth.", "名詞"),
    "union": ("聯盟", "The workers formed a union.", "名詞"),
    "universe": ("宇宙", "The universe is infinite.", "名詞"),
    "value": ("價值", "Family values are important.", "名詞"),
    "variety": ("多樣性", "The store offers a variety of products.", "名詞"),
    "victim": ("受害者", "Help the victims of the disaster.", "名詞"),
    "view": ("觀點、景色", "The view from here is beautiful.", "名詞"),
    "village": ("村莊", "I grew up in a small village.", "名詞"),
    "violence": ("暴力", "Violence is never the answer.", "名詞"),
    "voice": ("聲音", "I recognize your voice.", "名詞"),
    "volume": ("音量、體積", "Turn down the volume.", "名詞"),
    "vote": ("投票", "Every vote counts.", "名詞"),
    "war": ("戰爭", "War causes suffering.", "名詞"),
    "warning": ("警告", "Heed the warning.", "名詞"),
    "waste": ("浪費", "Don't waste food.", "名詞"),
    "wealth": ("財富", "Health is wealth.", "名詞"),
    "weather": ("天氣", "The weather is nice today.", "名詞"),
    "weight": ("重量", "What's your weight?", "名詞"),
    "wheel": ("輪子", "The wheel is flat.", "名詞"),
    "wind": ("風", "The wind is strong.", "名詞"),
    "wisdom": ("智慧", "Wisdom comes with age.", "名詞"),
    "witness": ("目擊者", "Call the witness to testify.", "名詞"),

    # Pronouns
    "I": ("我", "I am a student.", "代名詞"),
    "you": ("你", "You are my friend.", "代名詞"),
    "he": ("他", "He is my brother.", "代名詞"),
    "she": ("她", "She is my sister.", "代名詞"),
    "it": ("它", "It is a cat.", "代名詞"),
    "we": ("我們", "We are classmates.", "代名詞"),
    "they": ("他們", "They are students.", "代名詞"),
    "me": ("我（受格）", "Give it to me.", "代名詞"),
    "him": ("他（受格）", "I saw him yesterday.", "代名詞"),
    "her": ("她（受格）", "Tell her the news.", "代名詞"),
    "us": ("我們（受格）", "Join us for dinner.", "代名詞"),
    "them": ("他們（受格）", "I like them.", "代名詞"),
    "my": ("我的", "This is my book.", "代名詞"),
    "your": ("你的", "Is this your pen?", "代名詞"),
    "his": ("他的", "That's his car.", "代名詞"),
    "its": ("它的", "The dog wagged its tail.", "代名詞"),
    "our": ("我們的", "This is our school.", "代名詞"),
    "their": ("他們的", "That's their house.", "代名詞"),
    "mine": ("我的（東西）", "This book is mine.", "代名詞"),
    "yours": ("你的（東西）", "Is this pen yours?", "代名詞"),
    "hers": ("她的（東西）", "That bag is hers.", "代名詞"),
    "ours": ("我們的（東西）", "This classroom is ours.", "代名詞"),
    "theirs": ("他們的（東西）", "Those bikes are theirs.", "代名詞"),
    "myself": ("我自己", "I did it myself.", "代名詞"),
    "yourself": ("你自己", "Did you do it yourself?", "代名詞"),
    "himself": ("他自己", "He taught himself.", "代名詞"),
    "herself": ("她自己", "She lives by herself.", "代名詞"),
    "itself": ("它自己", "The door closed itself.", "代名詞"),
    "ourselves": ("我們自己", "We made it ourselves.", "代名詞"),
    "themselves": ("他們自己", "They enjoyed themselves.", "代名詞"),
    "this": ("這個", "This is my favorite song.", "代名詞"),
    "that": ("那個", "That is a good idea.", "代名詞"),
    "these": ("這些", "These are my friends.", "代名詞"),
    "those": ("那些", "Those are nice shoes.", "代名詞"),
    "who": ("誰", "Who is that person?", "代名詞"),
    "whom": ("誰（受格）", "Whom did you meet?", "代名詞"),
    "whose": ("誰的", "Whose book is this?", "代名詞"),
    "what": ("什麼", "What is your name?", "代名詞"),
    "which": ("哪一個", "Which color do you prefer?", "代名詞"),
    "where": ("哪裡", "Where are you going?", "代名詞"),
    "when": ("何時", "When will you arrive?", "代名詞"),
    "why": ("為什麼", "Why are you late?", "代名詞"),
    "how": ("如何", "How are you today?", "代名詞"),
    "anyone": ("任何人", "Can anyone help me?", "代名詞"),
    "someone": ("某人", "Someone is at the door.", "代名詞"),
    "everyone": ("每個人", "Everyone must attend.", "代名詞"),
    "no one": ("沒有人", "No one knows the answer.", "代名詞"),
    "nobody": ("沒有人", "Nobody came to the party.", "代名詞"),
    "somebody": ("某人", "Somebody called you.", "代名詞"),
    "everybody": ("每個人", "Everybody loves ice cream.", "代名詞"),
    "anything": ("任何事", "You can ask me anything.", "代名詞"),
    "something": ("某事", "I have something to tell you.", "代名詞"),
    "everything": ("每件事", "Everything will be okay.", "代名詞"),
    "nothing": ("沒有東西", "There's nothing in the box.", "代名詞"),
    "another": ("另一個", "Would you like another cookie?", "代名詞"),
    "other": ("其他的", "The other students left.", "代名詞"),
    "others": ("其他人", "Some like tea, others prefer coffee.", "代名詞"),
    "each": ("每個", "Each student has a book.", "代名詞"),
    "every": ("每個", "Every child needs love.", "代名詞"),
    "either": ("兩者之一", "You can choose either option.", "代名詞"),
    "neither": ("兩者都不", "Neither answer is correct.", "代名詞"),
    "both": ("兩者都", "Both students passed the test.", "代名詞"),
    "all": ("全部", "All the students are here.", "代名詞"),
    "some": ("一些", "Some people prefer tea.", "代名詞"),
    "any": ("任何", "Do you have any questions?", "代名詞"),
    "few": ("少數", "Few people came to the meeting.", "代名詞"),
    "many": ("許多", "Many students study English.", "代名詞"),
    "several": ("幾個", "Several books are missing.", "代名詞"),
    "most": ("大多數", "Most people like music.", "代名詞"),

    # Prepositions
    "in": ("在…裡面", "The book is in the bag.", "介係詞"),
    "on": ("在…上面", "Put it on the table.", "介係詞"),
    "at": ("在（地點/時間）", "I'm at school now.", "介係詞"),
    "to": ("到、向", "I go to school daily.", "介係詞"),
    "for": ("為了", "This gift is for you.", "介係詞"),
    "with": ("和、用", "I live with my family.", "介係詞"),
    "from": ("從", "I'm from Taiwan.", "介係詞"),
    "by": ("由、在…旁邊", "The book was written by her.", "介係詞"),
    "about": ("關於", "Tell me about your day.", "介係詞"),
    "up": ("向上", "Walk up the stairs.", "介係詞"),
    "down": ("向下", "Walk down the street.", "介係詞"),
    "out": ("向外", "Get out of here.", "介係詞"),
    "over": ("在…上方", "The bird flew over the house.", "介係詞"),
    "under": ("在…下面", "The cat is under the table.", "介係詞"),
    "into": ("進入", "Come into the room.", "介係詞"),
    "through": ("穿過", "Walk through the door.", "介係詞"),
    "between": ("在…之間", "Sit between your friends.", "介係詞"),
    "among": ("在…之中", "He stood among the crowd.", "介係詞"),
    "during": ("在…期間", "I slept during the movie.", "介係詞"),
    "before": ("在…之前", "Arrive before noon.", "介係詞"),
    "after": ("在…之後", "We'll eat after class.", "介係詞"),
    "until": ("直到", "Wait until I return.", "介係詞"),
    "since": ("自從", "I've lived here since 2010.", "介係詞"),
    "beside": ("在…旁邊", "Sit beside me.", "介係詞"),
    "behind": ("在…後面", "Hide behind the tree.", "介係詞"),
    "near": ("在…附近", "My house is near the school.", "介係詞"),
    "above": ("在…上方", "The plane flew above the clouds.", "介係詞"),
    "below": ("在…下方", "The temperature is below zero.", "介係詞"),
    "across": ("穿過", "Walk across the bridge.", "介係詞"),
    "along": ("沿著", "Walk along the river.", "介係詞"),
    "around": ("圍繞", "Walk around the park.", "介係詞"),
    "against": ("反對、靠著", "Lean against the wall.", "介係詞"),
    "within": ("在…之內", "Stay within the boundaries.", "介係詞"),
    "without": ("沒有", "I can't live without you.", "介係詞"),
    "toward": ("朝向", "Walk toward the exit.", "介係詞"),
    "towards": ("朝向", "She walked towards me.", "介係詞"),
    "throughout": ("遍及", "It rained throughout the day.", "介係詞"),
    "upon": ("在…上面", "Once upon a time...", "介係詞"),
    "off": ("離開", "Get off the bus here.", "介係詞"),
    "inside": ("在…裡面", "Wait inside the building.", "介係詞"),
    "outside": ("在…外面", "Meet me outside the cafe.", "介係詞"),
    "except": ("除了", "Everyone came except Tom.", "介係詞"),
    "besides": ("除了", "Besides English, I study math.", "介係詞"),
    "beyond": ("超出", "It's beyond my understanding.", "介係詞"),
    "despite": ("儘管", "Despite the rain, we went out.", "介係詞"),
    "via": ("經由", "Send it via email.", "介係詞"),
    "per": ("每", "It costs ten dollars per person.", "介係詞"),
    "plus": ("加上", "Two plus two equals four.", "介係詞"),
    "minus": ("減去", "Ten minus three is seven.", "介係詞"),

    # Conjunctions
    "and": ("和", "I like apples and oranges.", "連接詞"),
    "but": ("但是", "I like tea but not coffee.", "連接詞"),
    "or": ("或者", "Would you like tea or coffee?", "連接詞"),
    "so": ("所以", "I was tired, so I slept.", "連接詞"),
    "because": ("因為", "I'm happy because it's sunny.", "連接詞"),
    "if": ("如果", "If it rains, stay inside.", "連接詞"),
    "when": ("當", "Call me when you arrive.", "連接詞"),
    "while": ("當…的時候", "I read while waiting.", "連接詞"),
    "although": ("雖然", "Although tired, she continued.", "連接詞"),
    "though": ("雖然", "Though small, it's strong.", "連接詞"),
    "unless": ("除非", "Unless you hurry, we'll be late.", "連接詞"),
    "until": ("直到", "Wait until I return.", "連接詞"),
    "since": ("既然", "Since you're here, let's start.", "連接詞"),
    "as": ("當、因為", "As I said, we should go.", "連接詞"),
    "than": ("比", "She is taller than me.", "連接詞"),
    "whether": ("是否", "I wonder whether she'll come.", "連接詞"),
    "that": ("那", "I think that you're right.", "連接詞"),
    "where": ("哪裡", "This is where I live.", "連接詞"),
    "before": ("在…之前", "Call before you come.", "連接詞"),
    "after": ("在…之後", "We'll talk after dinner.", "連接詞"),
    "for": ("因為", "I'm glad, for she arrived safely.", "連接詞"),
    "nor": ("也不", "I don't like tea nor coffee.", "連接詞"),
    "yet": ("然而", "She's young, yet wise.", "連接詞"),
    "either": ("或者", "Either come now or don't come.", "連接詞"),
    "neither": ("既不", "Neither rain nor snow will stop us.", "連接詞"),
    "both": ("兩者都", "Both you and I must go.", "連接詞"),
    "not": ("不", "It's not that simple.", "連接詞"),
    "once": ("一旦", "Once you start, don't stop.", "連接詞"),
    "provided": ("假如", "You can go, provided you finish.", "連接詞"),
    "assuming": ("假設", "Assuming he's right, what next?", "連接詞"),
}

def get_word_data(word):
    """
    Get definition, sentence, and part of speech for a word.
    Returns tuple of (definition, sentence, part_of_speech).
    """
    word_lower = word.lower()

    # Check comprehensive dictionary first
    if word_lower in COMPREHENSIVE_DICTIONARY:
        return COMPREHENSIVE_DICTIONARY[word_lower]

    # Try to infer based on common patterns
    # This section handles words not in our comprehensive dictionary

    # Common verb endings
    if word_lower.endswith('ing'):
        base = word_lower[:-3]
        if base.endswith('e'):
            base = base[:-1]
        return (f"{word}（動詞進行式）", f"She is {word} right now.", "動詞")

    if word_lower.endswith('ed'):
        base = word_lower[:-2]
        if base.endswith('e'):
            base = base[:-1]
        return (f"{word}（動詞過去式）", f"They {word} yesterday.", "動詞")

    # Common noun endings with better sentences
    if word_lower.endswith('tion') or word_lower.endswith('sion'):
        return (f"{word}（名詞）", f"We need better {word} in this process.", "名詞")

    if word_lower.endswith('ment'):
        return (f"{word}（名詞）", f"This {word} requires careful attention.", "名詞")

    if word_lower.endswith('ness'):
        return (f"{word}（名詞）", f"Their {word} impressed everyone.", "名詞")

    if word_lower.endswith('ity') or word_lower.endswith('ty'):
        return (f"{word}（名詞）", f"The {word} of this matter is clear.", "名詞")

    # Common adjective endings with better sentences
    if word_lower.endswith('ful'):
        return (f"充滿{word[:-3]}的", f"It was a {word} experience for everyone.", "形容詞")

    if word_lower.endswith('less'):
        return (f"沒有{word[:-4]}的", f"The situation appeared completely {word}.", "形容詞")

    if word_lower.endswith('ous') or word_lower.endswith('ious'):
        return (f"{word}的", f"That was a {word} achievement.", "形容詞")

    if word_lower.endswith('ive'):
        return (f"{word}的", f"We need a more {word} approach.", "形容詞")

    if word_lower.endswith('able') or word_lower.endswith('ible'):
        return (f"可{word[:-4]}的", f"This solution is quite {word}.", "形容詞")

    if word_lower.endswith('al'):
        return (f"{word}的", f"This is a {word} issue we must address.", "形容詞")

    # Common adverb ending
    if word_lower.endswith('ly'):
        base = word_lower[:-2]
        return (f"以{base}的方式", f"She speaks {word}.", "副詞")

    # Default fallback based on word length and complexity
    if len(word) <= 4:
        # Short words are often verbs or nouns
        return (f"{word}（詞）", f"We should {word} more carefully.", "動詞")
    else:
        # Longer words default to nouns
        return (f"{word}（名詞）", f"Understanding {word} is essential for learning.", "名詞")

def is_placeholder(text, word):
    """Check if text is a placeholder that needs to be replaced"""
    if not text:
        return True
    if "的中文意思" in text:
        return True
    # Check for bad sentences
    bad_patterns = [
        f"The {word} was found",
        f"The {word} is important",
        f"This {word} is useful",
        f"I need a {word}",
        f"We have a {word}",
        f"We must {word}",
        f"She can {word}",
        f"He can {word}",
        "was found",
        "is useful",
        "is important",
        "can led",
        "can saw",
        "can went",
        "can came",
        "can ran",
        "must seeing",
        "must going"
    ]
    for pattern in bad_patterns:
        if pattern.lower() in text.lower():
            return True
    return False

def fix_entry(entry):
    """Fix a single word entry with proper definition, sentence, and part of speech"""
    word = entry.get("word", "").strip()
    if not word:
        return entry

    definition = entry.get("definition", "")
    sentence = entry.get("sentence", "")
    pos = entry.get("partOfSpeech", "")

    # Get correct data for this word
    correct_def, correct_sent, correct_pos = get_word_data(word)

    word_lower = word.lower()
    in_dictionary = word_lower in COMPREHENSIVE_DICTIONARY

    # Replace definition
    # If in our dictionary, always use our definition
    # Otherwise, only if placeholder
    if in_dictionary:
        entry["definition"] = correct_def
    elif is_placeholder(definition, word):
        entry["definition"] = correct_def

    # Replace sentence
    # If in our dictionary, always use our sentence
    # Otherwise, only if placeholder
    if in_dictionary:
        entry["sentence"] = correct_sent
    elif is_placeholder(sentence, word):
        entry["sentence"] = correct_sent

    # Fix part of speech
    # If we have the word in our dictionary, trust our classification
    if in_dictionary:
        entry["partOfSpeech"] = correct_pos
    else:
        # For other words, only update if not already in valid Chinese
        chinese_pos = ["名詞", "動詞", "形容詞", "副詞", "代名詞", "介係詞", "連接詞", "感嘆詞"]
        if pos not in chinese_pos:
            entry["partOfSpeech"] = correct_pos

    return entry

def process_file(filepath, filename):
    """Process a single JSON file"""
    print(f"\nProcessing {filename}...")
    print(f"Reading from: {filepath}")

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        total = len(data)
        print(f"Total entries: {total}")

        # Fix each entry
        for i in range(total):
            data[i] = fix_entry(data[i])
            if (i + 1) % 100 == 0:
                print(f"  Progress: {i + 1}/{total} ({(i+1)*100//total}%)")

        # Write back with proper formatting
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"✓ Completed {filename} - {total} entries fixed")
        return total

    except Exception as e:
        print(f"✗ Error processing {filename}: {str(e)}")
        return 0

def main():
    base_path = "/Users/jeffkuo/My Drive/AIProjects/spellingbee/src/gameTypes/english-spelling/data"

    files = [
        "elementary.json",
        "middle.json",
        "high.json",
        "university.json",
        "expert.json"
    ]

    print("=" * 60)
    print("SPELLING BEE DICTIONARY CORRECTION SCRIPT")
    print("=" * 60)
    print(f"\nComprehensive dictionary contains {len(COMPREHENSIVE_DICTIONARY)} words")
    print("\nStarting file processing...")

    total_fixed = 0
    for filename in files:
        filepath = os.path.join(base_path, filename)
        if os.path.exists(filepath):
            count = process_file(filepath, filename)
            total_fixed += count
        else:
            print(f"\n✗ Warning: {filepath} not found")

    print("\n" + "=" * 60)
    print(f"COMPLETED: {total_fixed} total entries processed")
    print("=" * 60)

if __name__ == "__main__":
    main()
