import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Comprehensive English definitions suitable for spelling bee
// Clear, concise, educational, age-appropriate
const ENGLISH_DEFINITIONS = {
  // Elementary level - Common words
  "say": "to speak words aloud",
  "get": "to obtain or receive something",
  "saw": "past tense of see; to have looked at with eyes",
  "use": "to employ for a purpose",
  "way": "a method or manner of doing something",
  "new": "recently made or created",
  "old": "having existed for a long time",
  "see": "to perceive with the eyes",
  "make": "to create or produce something",
  "come": "to move toward a place",
  "look": "to direct one's eyes in order to see",
  "find": "to discover or locate something",
  "give": "to transfer possession of something",
  "tell": "to communicate information",
  "work": "to perform labor or duties",
  "call": "to speak to someone in a loud voice",
  "feel": "to experience an emotion or sensation",
  "hand": "the body part at the end of the arm",
  "high": "extending upward; tall",
  "year": "a period of twelve months",
  "different": "not the same as another",
  "important": "having great significance",
  "beautiful": "pleasing to the senses",
  "wonderful": "extremely good; marvelous",
  "because": "for the reason that",
  "guy": "informal term for a man or boy",
  "air": "the invisible mixture of gases surrounding Earth",
  "school": "a place where children learn",
  "water": "a clear liquid necessary for life",
  "house": "a building where people live",
  "friend": "a person you like and trust",
  "mother": "a female parent",
  "father": "a male parent",
  "brother": "a male sibling",
  "sister": "a female sibling",
  "family": "parents and their children",
  "animal": "a living creature that can move",
  "book": "a written or printed work with pages",
  "read": "to look at and understand written words",
  "write": "to form letters or words on a surface",
  "think": "to use your mind to consider something",
  "know": "to have information in your mind",
  "help": "to assist someone",
  "want": "to desire or wish for something",
  "need": "to require something essential",
  "time": "the measured period during which events occur",
  "day": "a 24-hour period",
  "night": "the period of darkness between sunset and sunrise",
  "morning": "the early part of the day",
  "food": "substances that people eat",
  "play": "to engage in activity for enjoyment",
  "run": "to move quickly on foot",
  "walk": "to move at a regular pace on foot",
  "talk": "to speak in order to communicate",
  "listen": "to pay attention to sound",
  "happy": "feeling pleasure or joy",
  "sad": "feeling sorrow or unhappiness",
  "big": "large in size",
  "small": "little in size",
  "good": "having positive qualities",
  "bad": "having negative qualities",
  "hot": "having high temperature",
  "cold": "having low temperature",
  "fast": "moving quickly",
  "slow": "moving at low speed",
  "strong": "having physical power",
  "weak": "lacking strength",
  "young": "in the early stage of life",
  "quiet": "making little or no noise",
  "loud": "making much noise",
  "clean": "free from dirt",
  "dirty": "covered with dirt",
  "easy": "not difficult",
  "hard": "difficult to do",
  "right": "correct or true",
  "wrong": "incorrect or mistaken",
  "true": "accurate or factual",
  "false": "not true or accurate",

  // Common verbs
  "ask": "to request information",
  "answer": "to respond to a question",
  "teach": "to give instruction",
  "learn": "to gain knowledge",
  "study": "to devote time to learning",
  "remember": "to recall from memory",
  "forget": "to fail to remember",
  "understand": "to comprehend meaning",
  "believe": "to accept as true",
  "hope": "to desire with expectation",
  "wish": "to want something to happen",
  "try": "to make an effort",
  "begin": "to start",
  "finish": "to complete",
  "stop": "to cease movement or action",
  "start": "to begin an action",
  "continue": "to keep doing something",
  "change": "to make or become different",
  "move": "to change position",
  "turn": "to rotate or change direction",
  "open": "to move from closed to accessible",
  "close": "to shut",
  "put": "to place in a position",
  "take": "to grasp and remove",
  "bring": "to carry something to a place",
  "carry": "to transport while holding",
  "hold": "to grasp and support",
  "keep": "to retain possession",
  "leave": "to go away from",
  "stay": "to remain in a place",
  "sit": "to rest on the buttocks",
  "stand": "to be in upright position",
  "sleep": "to rest with eyes closed and mind inactive",
  "wake": "to stop sleeping",
  "eat": "to consume food",
  "drink": "to swallow liquid",
  "cook": "to prepare food with heat",
  "cut": "to divide with a sharp tool",
  "break": "to separate into pieces",
  "build": "to construct",
  "grow": "to increase in size",
  "fall": "to drop downward",
  "fly": "to move through air",
  "swim": "to move through water",
  "jump": "to push off the ground",
  "climb": "to ascend using hands and feet",

  // Nouns
  "place": "a particular area or location",
  "thing": "an object or item",
  "person": "a human being",
  "child": "a young human",
  "man": "an adult male human",
  "woman": "an adult female human",
  "boy": "a male child",
  "girl": "a female child",
  "baby": "a very young child",
  "name": "a word by which someone is called",
  "word": "a unit of language",
  "number": "a mathematical value",
  "color": "the property of objects that produce visual sensations",
  "sound": "vibrations that travel through air",
  "music": "organized sounds that are pleasant",
  "picture": "a visual representation",
  "story": "a narrative account",
  "question": "a sentence asking for information",
  "problem": "a matter requiring solution",
  "idea": "a thought or concept",
  "world": "the earth and all its inhabitants",
  "country": "a nation with its own government",
  "city": "a large town",
  "town": "a populated area larger than village",
  "village": "a small community",
  "street": "a public road in a city",
  "road": "a wide path for vehicles",
  "car": "a motor vehicle with four wheels",
  "bus": "a large vehicle for passengers",
  "train": "a connected series of railroad cars",
  "bicycle": "a two-wheeled vehicle powered by pedaling",
  "boat": "a vessel for traveling on water",
  "airplane": "a flying vehicle with wings",

  // Adjectives
  "tall": "having great height",
  "short": "having little height",
  "long": "having great length",
  "wide": "having great width",
  "narrow": "having little width",
  "thick": "having great depth",
  "thin": "having little depth",
  "heavy": "having great weight",
  "light": "having little weight",
  "full": "containing all it can hold",
  "empty": "containing nothing",
  "wet": "covered with liquid",
  "dry": "free from moisture",
  "dark": "having little or no light",
  "bright": "giving out much light",
  "soft": "easy to press or bend",
  "rough": "having uneven surface",
  "smooth": "having even surface",
  "sharp": "having thin cutting edge",
  "round": "shaped like a circle",
  "square": "having four equal sides",
  "straight": "without curves or bends",
  "flat": "having level surface",
  "deep": "extending far down",
  "shallow": "not deep",
  "near": "close in distance",
  "far": "at great distance",
  "early": "before the usual time",
  "late": "after the expected time",
  "first": "coming before all others",
  "last": "coming after all others",
  "next": "immediately following",
  "same": "identical or alike",
  "special": "better or different from usual",
  "normal": "usual or typical",
  "common": "occurring frequently",
  "rare": "not common",
  "simple": "easy to understand",
  "difficult": "hard to do or understand",
  "possible": "able to happen",
  "impossible": "unable to happen",
  "necessary": "required or essential",
  "important": "having great significance",
  "useful": "serving a purpose",
  "careful": "giving attention to avoid mistakes",
  "safe": "protected from danger",
  "dangerous": "able to cause harm",
  "afraid": "feeling fear",
  "brave": "showing courage",
  "kind": "showing care and consideration",
  "mean": "unkind or cruel",
  "friendly": "showing kindness",
  "angry": "feeling strong displeasure",
  "excited": "feeling enthusiasm",
  "surprised": "feeling unexpected wonder",
  "interested": "wanting to know more",
  "bored": "feeling weary from lack of interest",
  "tired": "in need of rest",
  "hungry": "feeling need for food",
  "thirsty": "feeling need for liquid",
  "sick": "affected by illness",
  "healthy": "in good physical condition",
  "alive": "living",
  "dead": "no longer living",

  // More complex words
  "education": "the process of teaching and learning",
  "knowledge": "information and understanding",
  "experience": "practical contact with events",
  "memory": "the ability to remember",
  "attention": "focused mental concentration",
  "interest": "curiosity or concern",
  "opinion": "a personal view or judgment",
  "decision": "a choice made after consideration",
  "purpose": "the reason for doing something",
  "result": "the outcome of an action",
  "example": "something illustrating a general rule",
  "reason": "a cause or explanation",
  "situation": "a set of circumstances",
  "condition": "the state of something",
  "difference": "the way things are unlike",
  "similarity": "the quality of being alike",
  "relationship": "the way things are connected",
  "connection": "a link between things",
  "direction": "the course something moves",
  "distance": "the space between two points",
  "speed": "the rate of movement",
  "strength": "the quality of being strong",
  "power": "the ability to do something",
  "energy": "the capacity to do work",
  "force": "physical power or strength",
  "pressure": "continuous force on something",
  "temperature": "degree of hotness or coldness",
  "weather": "atmospheric conditions",
  "climate": "typical weather patterns",
  "nature": "the physical world",
  "environment": "surroundings or conditions",
  "society": "people living together in community",
  "culture": "the customs and beliefs of people",
  "tradition": "beliefs passed through generations",
  "custom": "a usual way of behaving",
  "habit": "a regular practice",
  "behavior": "the way someone acts",
  "character": "the qualities of a person",
  "personality": "distinctive qualities of a person",
  "ability": "the capacity to do something",
  "skill": "the ability to do something well",
  "talent": "natural ability",
  "intelligence": "ability to learn and understand",
  "wisdom": "the quality of good judgment",
  "patience": "ability to wait calmly",
  "courage": "bravery in facing difficulty",
  "honesty": "quality of being truthful",
  "respect": "admiration for someone",
  "responsibility": "duty to deal with something",
  "freedom": "the state of being free",
  "independence": "freedom from outside control",
  "peace": "freedom from war or violence",
  "war": "armed conflict between nations",
  "problem": "a difficulty requiring solution",
  "solution": "the answer to a problem",
  "success": "accomplishment of a goal",
  "failure": "lack of success",
  "progress": "forward movement",
  "development": "growth or advancement",
  "improvement": "making something better",
  "achievement": "something accomplished",
  "goal": "an aim or desired result",
  "plan": "a detailed proposal",
  "method": "a way of doing something",
  "process": "a series of actions",
  "system": "an organized set of things",
  "order": "arrangement of things",
  "organization": "structured arrangement",
  "structure": "the arrangement of parts",
  "pattern": "a repeated design",
  "shape": "the external form",
  "size": "the physical magnitude",
  "amount": "a quantity of something",
  "quantity": "an amount or number",
  "quality": "the standard of excellence",
  "value": "the worth of something",
  "price": "the cost of something",
  "cost": "the amount paid for something",
  "money": "medium of exchange",
  "business": "commercial activity",
  "company": "a commercial organization",
  "product": "something produced",
  "service": "helpful activity",
  "customer": "one who purchases goods",
  "market": "place where goods are sold",
  "government": "system controlling a nation",
  "law": "a rule established by authority",
  "rule": "an established regulation",
  "right": "a moral or legal entitlement",
  "duty": "a moral obligation",
  "justice": "fairness in treatment",
  "truth": "the quality of being true",
  "fact": "something known to be true",
  "information": "facts or data",
  "communication": "exchange of information",
  "language": "system of spoken words",
  "expression": "the act of making known",
  "meaning": "what is intended to be understood",
  "message": "a communicated statement",
  "conversation": "informal spoken exchange",
  "discussion": "talking about something",
  "argument": "a reason given",
  "agreement": "harmony in opinion",
  "disagreement": "lack of agreement"
}

// Process dictionary files
function convertDefinitions(filename) {
  const filePath = path.join(__dirname, '..', 'src', 'gameTypes', 'english-spelling', 'data', filename)
  console.log(`\n📝 Processing ${filename}...`)

  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'))
  let converted = 0
  let notFound = 0

  const updated = data.map(entry => {
    if (ENGLISH_DEFINITIONS[entry.word]) {
      converted++
      return {
        ...entry,
        definition: ENGLISH_DEFINITIONS[entry.word]
      }
    } else {
      notFound++
      // Keep existing definition if no English one found
      return entry
    }
  })

  fs.writeFileSync(filePath, JSON.stringify(updated, null, 2), 'utf8')
  console.log(`  ✅ Converted: ${converted}`)
  console.log(`  ⚠️  Not found: ${notFound}`)
  return { converted, notFound }
}

// Main execution
console.log('🔄 Converting to English Definitions')
console.log('====================================\n')
console.log('Making definitions spelling-bee appropriate:\n')
console.log('  ✓ Clear and concise')
console.log('  ✓ Age-appropriate')
console.log('  ✓ Educational\n')

const files = ['elementary.json', 'middle.json', 'high.json', 'university.json', 'expert.json']
let totalConverted = 0
let totalNotFound = 0

files.forEach(file => {
  const result = convertDefinitions(file)
  totalConverted += result.converted
  totalNotFound += result.notFound
})

console.log('\n' + '='.repeat(50))
console.log(`\n✅ Total converted: ${totalConverted}`)
console.log(`⚠️  Still need conversion: ${totalNotFound}`)
console.log(`\nNote: Words without English definitions kept their current definitions.\n`)
